apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-bigquery-DINAPP
  namespace: okonomi
  labels:
    "team": okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  webproxy: true
  envFrom:
    - secret: database-credentials
    - secret: bigquery-credentials
  filesFrom:
    - secret: db2license

  resources:
    requests:
      cpu: 3000m
      memory: 32Gi
  ingresses:
    - https://sokos-bigquery-DINAPP.dev.intern.nav.no
    - https://sokos-bigquery-DINAPP.dev-fss-pub.nais.io
  env:
    - name: DATABASE_HOST
      value: "din host her"
    - name: DATABASE_PORT
      value: "din port her"
    - name: DATABASE_NAME
      value: "databasenavn her"
    - name: DATABASE_SCHEMA
      value: "schema her"
    - name: HIKARI_TEST_TABLE
      value: "tabell for hikari connection test"